[[redirects]]
  from = "/"
  to = "/en/"
  status = 302

[[redirects]]
  from = "/en"
  to = "/en/"
  status = 301

[[redirects]]
  from = "/ru"
  to = "/ru/"
  status = 301

[[redirects]]
  from = "/en/"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/ru/"
  to = "/ru/index.html"
  status = 200
